Data retention für kalibrierte Waagenwerte und init-flag hinzugefügt
binsim/postmelder pull request #52
Opened 2023-12-01 10:24 UTC by floergri

- speichert die ermittelten Wägezellenwerte in den Flash
- liest diese aus, wenn bereits initialisiert
- wenn WIPE als 'true' definiert wird, wird die User-Partition formatiert und alle gespeicherten Werte gelöscht

2023-12-01 12:37 UTC, binsim requested changes
Schaut grundsätzlich gut aus, sehe ein großes Problem bei deiner `while`-Schleife, die wird den Rest des Programms ziemlich blockieren. Nutze hierfür am Besten die Funktionalität der `loop`-Funktion aus und speichere Informationen, die du für spätere Wiederholungen brauchst, einfach mit einer _statischen Variable_ ab, dann kann auch nichts blockiert werden. 

Grundsätzlich müsstest du bessere Namen vergeben bzw. auf die Nameskonventionen achten, die gibt es nicht ohne Grund. Habe da hoffentlich die groben Sachen etwas ausgebessert.

Auch wäre es nicht schlecht, wenn du Variablen, die du nicht brauchst auch wieder löschen und auch nicht alles so __global__ machen würdest, dass kann eventuell mal im späteren Verlauf zu Problemen führen.

2023-12-01 12:37 UTC, binsim commented on esp-client/src/main.cpp
>  	}
Würde da lieber weiter machen mit einer Fehleranzeige. Eventuell könnte man dann auch den Fehler über MQTT senden, dass da das mit der Waage nicht stimmt

2023-12-01 12:37 UTC, binsim commented on esp-client/src/main.cpp
> +		scale.set_scale(scaleValue);
Würde das mit dem Issue [#53](https://github.com/binsim/postmelder/issues/53) fixen, würde dann anders ausschauen. Beim Starten zu kalibrieren find ich nicht so gut

2023-12-01 12:37 UTC, binsim commented on esp-client/src/main.cpp
>  	weight = readScale();
Gewicht würde ich nicht im `setup` auslesen

2023-12-01 12:37 UTC, binsim commented on esp-client/src/main.cpp
>  		}
Das wird zu Problemen führen, mach das am Besten ohne Schleife, du hast ja die `loop` Funktion, die wird ja dauernd aufgerufen. Dann brauchst du auch die `weightChange` Variable nicht global machen

2023-12-01 12:37 UTC, binsim commented on esp-client/src/main.cpp
> +bool scaleInitialised; // saves whether the scale has already been calibrated-> Flash
Muss `scaleInitialised` wirklich global sein, das ist doch nur für setup interessant?

2023-12-01 12:37 UTC, binsim commented on esp-client/src/main.cpp
> +Preferences preferences; // preferences object
Wenn du das `preferences` Objekt nur im `setup` benutzt, kannst du es auch lokal machen

2023-12-08 08:36 UTC, binsim approved these changes

2023-12-08 08:45 UTC, EliasLGR approved these changes

2023-12-08 08:46 UTC, merged