Erkennen von Wägezellenproblemen und setzen des states umgesetzt
binsim/postmelder pull request #71
Opened 2024-01-06 10:30 UTC by floergri

- Zählt mit, wie oft sich das Gewicht ändert und setzt zurück auf null wenn eingependelt
- wenn Wägezelle nicht angeschlossen oder ähnlich, dann random Werte -> pendelt sich nicht ein
- wenn mehr als 50 `hops`, dann Fehler

2024-01-06 12:42 UTC, EliasLGR approved these changes

2024-01-06 13:30 UTC, binsim requested changes

2024-01-06 13:30 UTC, binsim commented on esp-client/lib/Scale/Scale.cpp
> +		hops++; //increase counter
Überlegung ist, ob man da eventuell einen _Integer Overflow_ überprüft zu vermeiden

2024-01-06 13:30 UTC, binsim commented on esp-client/lib/Scale/Scale.h
> +	int hops;
Könnte man eventuell auch `unsigned` machen, da ja keine negativen Zahlen gewünscht sind

2024-01-08 17:29 UTC, binsim requested changes

2024-01-08 17:29 UTC, binsim commented on esp-client/lib/Scale/Scale.cpp
> +
Formatierung!!!

2024-01-08 17:29 UTC, binsim commented on esp-client/lib/Scale/Scale.cpp
> +	}
Könnte man gleich den `if` zurückgeben. `Serial.println` braucht man nicht, wird ja der State angezeigt

2024-01-08 18:35 UTC, binsim approved these changes

2024-01-08 18:37 UTC, merged